# AMD vs Intel Dataset

<b>Compas, Gabriel Zion T09</b>
<br>Computer Engineer

In [1]:
# imports and packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# load dataset
df = pd.read_csv(r"dataset/AMDvsIntelSpeed.csv")
df[["AMD","Intel"]].head(30)

    AMD  Intel
0   3.0    3.0
1   3.0    2.6
2   3.5    3.1
3   3.5    2.8
4   3.4    3.3
5   3.5    3.1
6   3.8    3.5
7   2.8    2.9
8   3.7    3.5
9   3.2    3.3
10  3.6    3.3
11  3.4    3.6
12  3.0    3.8
13  4.7    3.5
14  4.4    4.3
15  3.3    4.0
16  4.0    3.6
17  4.0    3.0
18  3.2    3.0
19  3.5    3.2
20  3.3    3.6
21  3.9    3.5
22  3.5    3.4
23  3.8    3.3
24  3.3    3.6
25  4.2    3.7
26  4.0    4.2
27  3.8    4.0
28  3.8    3.2
29  3.6    3.6

In [12]:
# summary of dataframe
df[["AMD","Intel"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AMD     30 non-null     float64
 1   Intel   30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [4]:
# summary of statistics (raw data - non-normal)
df[["Solar","Wind"]].describe()

              Solar          Wind
count  54170.000000  54170.000000
mean     171.808381    771.727691
std      257.257698    666.534396
min        0.000000    -26.000000
25%        0.000000    228.000000
50%        3.000000    571.000000
75%      302.000000   1167.000000
max     1552.000000   2811.000000

## Apply Central Limit Theorem

In [ ]:
# storage of means
means_data = {"AMD": [], "Intel": []}

np.random.seed(42)

# sampling means
for _ in range(50): 
    for c in ["AMD", "Intel"]:
        sample = np.random.choice(df[c], size=30, replace=True)
        means_data[c].append(np.mean(sample))

In [14]:
df_means = pd.DataFrame(means_data)
df_means

         AMD     Intel
0   3.540000  3.590000
1   3.726667  3.443333
2   3.513333  3.400000
3   3.703333  3.533333
4   3.600000  3.363333
5   3.560000  3.430000
6   3.496667  3.326667
7   3.580000  3.360000
8   3.670000  3.416667
9   3.493333  3.496667
10  3.683333  3.383333
11  3.480000  3.303333
12  3.596667  3.503333
13  3.703333  3.343333
14  3.583333  3.490000
15  3.560000  3.446667
16  3.576667  3.353333
17  3.626667  3.373333
18  3.430000  3.436667
19  3.796667  3.556667
20  3.556667  3.416667
21  3.523333  3.323333
22  3.556667  3.373333
23  3.460000  3.390000
24  3.576667  3.396667
25  3.623333  3.523333
26  3.706667  3.393333
27  3.470000  3.406667
28  3.466667  3.410000
29  3.593333  3.480000
30  3.616667  3.346667
31  3.556667  3.610000
32  3.653333  3.450000
33  3.600000  3.506667
34  3.580000  3.363333
35  3.603333  3.400000
36  3.490000  3.370000
37  3.800000  3.406667
38  3.656667  3.540000
39  3.676667  3.400000
40  3.556667  3.416667
41  3.593333  3.390000
42  3.576667  3.390000
43  3.600000  3.426667
44  3.690000  3.410000
45  3.610000  3.430000
46  3.496667  3.423333
47  3.586667  3.533333
48  3.580000  3.596667
49  3.533333  3.446667

In [16]:
df_means.to_csv(r"dataset/AMDvsIntel-clt-dataset.csv", index=False)
print("CLT dataset saved!")

CLT dataset saved!